<a href="https://colab.research.google.com/github/ChetanGoud77/PYTHON/blob/main/DAY_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
a=88,75,98 ,47,99,36,77

In [2]:
a

(88, 75, 98, 47, 99, 36, 77)

In [4]:
import numpy as np
random_numbers = np.random.randint(0, 101, size=10)
random_numbers

array([64, 19, 52, 80, 69,  3, 73, 12, 90, 25])

In [5]:
a

(88, 75, 98, 47, 99, 36, 77)

In [6]:
a[5]

36

In [11]:
np.random.seed(88)
a=np.random.randint(45,78,(7,8))
a

array([[69, 77, 60, 65, 50, 56, 49, 52],
       [71, 70, 52, 51, 55, 67, 74, 58],
       [58, 46, 59, 59, 56, 61, 77, 50],
       [66, 48, 75, 70, 58, 48, 68, 58],
       [73, 69, 66, 73, 61, 45, 56, 73],
       [66, 56, 75, 70, 46, 67, 59, 60],
       [62, 72, 52, 49, 67, 73, 51, 51]])

In [13]:
a[4]

array([73, 69, 66, 73, 61, 45, 56, 73])

In [14]:
a[5,6]

59

In [15]:
a[1:5,1:5]

array([[70, 52, 51, 55],
       [46, 59, 59, 56],
       [48, 75, 70, 58],
       [69, 66, 73, 61]])

In [16]:
a[1:7,1:7]

array([[70, 52, 51, 55, 67, 74],
       [46, 59, 59, 56, 61, 77],
       [48, 75, 70, 58, 48, 68],
       [69, 66, 73, 61, 45, 56],
       [56, 75, 70, 46, 67, 59],
       [72, 52, 49, 67, 73, 51]])

In [18]:
import numpy as np
np.random.seed(88)
a=np.random.randint(45,78,(7,8))
a[1:7,1:7] * -1

array([[-70, -52, -51, -55, -67, -74],
       [-46, -59, -59, -56, -61, -77],
       [-48, -75, -70, -58, -48, -68],
       [-69, -66, -73, -61, -45, -56],
       [-56, -75, -70, -46, -67, -59],
       [-72, -52, -49, -67, -73, -51]])

In [23]:
a[-5:-1,-6:-1]

array([[59, 59, 56, 61, 77],
       [75, 70, 58, 48, 68],
       [66, 73, 61, 45, 56],
       [75, 70, 46, 67, 59]])

In [25]:
a[2:3]

array([[58, 46, 59, 59, 56, 61, 77, 50]])

In [30]:
np.where(a>20)

(array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2,
        2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5,
        5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5,
        6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3,
        4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7]))